
on:
  push:
    branches:
      - gpstaging.v14.3.1

name: Deploy to ERPNext Staging Env

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd greenphyto_docker/frappe_docker/
          docker compose --project-name erpnext-greenphyto -f ~/gitops/erpnext-greenphyto.yaml down
          docker ps
          docker builder prune -a -f
          docker image prune -a -f
          docker buildx bake --load
          docker compose --project-name erpnext-greenphyto -f ~/gitops/erpnext-greenphyto.yaml up -d
          docker ps
          echo 'finished deployment'
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Required mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Required mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: ERPNext Staging Deployment Done
        # Required recipients' addresses:
        to: weiquan@greenphyto.com,myo@greenphyto.com,aunt.maung@greenphyto.com
        # Required sender full name (address can be skipped):
        from: Info@greenphyto.com # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: ERPNext staging deployment done! URL-https://erp-staging.greenphyto.com
       
