on:
  push:
    branches:
      - gpcandidate.v14.3.1

name: Deploy to ERPNext Candidate Environment

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .

    steps:
    - name: executing remote ssh to build server and upload docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ON_PREMISE_HOST }}
        username: ${{ secrets.ON_PREMISE_USERNAME }}
        key: ${{ secrets.ON_PREMISE_KEY }}
        port: ${{ secrets.ON_PREMISE_PORT }}
        command_timeout: 30m
        script_stop: true
        script: |
          cd greenphyto/erpnextbuild/candidate01/frappe_docker/
          export FRAPPE_VERSION=gp.v14.12.0
          docker buildx bake --load -f docker-bake.hcl 
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com
          docker tag frappe/erpnext-nginx:gpcandidate.v14.3.1 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext:latest
          docker push 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext:latest
          docker tag frappe/erpnext-worker:gpcandidate.v14.3.1 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext.worker:latest
          docker push 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext.worker:latest
          docker tag frappe/frappe-socketio:gp.v14.12.0 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext:socketio-latest
          docker push 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext:socketio-latest
          echo 'upload finished'
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CANDIDATE_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script_stop: true
        script: |
          cd greenphyto_docker/frappe_docker/
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com
          docker pull 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext:latest
          docker pull 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext.worker:latest
          docker pull 277077783554.dkr.ecr.ap-southeast-1.amazonaws.com/greenphyto.erpnext:socketio-latest
          docker compose --project-name erpnext-greenphyto -f ~/gitops/erpnext-greenphyto-aws.yaml down
          docker ps
          docker compose --project-name erpnext-greenphyto -f ~/gitops/erpnext-greenphyto-aws.yaml up -d
          docker ps
          echo 'finished deployment'
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Required mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Required mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: ERPNext Candidate Deployment Done
        # Required recipients' addresses:
        to: weiquan@greenphyto.com,myo@greenphyto.com,rizky@greenphyto.com
        # Required sender full name (address can be skipped):
        from: Info@greenphyto.com # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: ERPNext deployment done for candidate env! Branch - gpcandidate.v14.3.1, Commit Description - ${{github.event.head_commit.message}} URL-https://erp-candidate-01.greenphyto.com
       
